name: Push-to-VPS

# Trigger deployment only on push to master branch
on:
  push:
    branches: [ main ]


jobs:
  build:
    name: Deploy to VPS on main branch push
    runs-on: ubuntu-20.04


    steps:
      - name: Checkout the files
      - uses: actions/checkout@v2
      - name: Use Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: Install dependencies
      - run: npm install
      - name: run app
      - run: npm start

  deploy:
    runs-on: ubuntu-20.04
    needs: [build] 
    steps:
      - uses: actions/checkout@v2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSHKEY }}
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.DIR }}

   