name: Deploy-to-VPS

 #Trigger deployment only on push to main branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VPS on main branch push
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2


      - name: Deploy to Sams VPS
        uses: ngalande/eToll_Broker@main
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}


