name: Deploy
 
on: [push]
 
jobs:
  build:
 
    runs-on: ubuntu-22.04
 
    steps:
    - uses: actions/checkout@v1
 
    - name: Copy repository contents via scp
      uses: ngalande/eToll_Broker@main
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/var/www/html/eToll_Broker"
 
    - name: Executing remote command
      uses: ngalande/eToll_Broker@main
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: ls