name: Push-to-VPS

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VPS on main branch push
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: actions/checkout@v2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSHKEY }}
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.DIR }}
          script: |
            cd /var/www/html/eToll_Broker
            git pull origin main
            git status
            npm install
            pm2 restart etollbroker
            # ngalande/e-Toll_Broker@main